version: '3'
services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: url-shortner
    container_name: express-app
    environment:
      - MONGO_URI=mongodb://mongo:27017/url-shortner
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
volumes:
  mongo-data: